// AI provider definitions — pure constants, no logic

export const AI_PROVIDERS = {
  claude: {
    id: 'claude',
    name: 'Claude (Anthropic)',
    description: 'Anthropic\'s Claude — excellent reasoning and analysis',
    model: 'claude-sonnet-4-20250514',
    keyField: 'anthropicApiKey',
    keyPrefix: 'sk-ant-',
    keyPlaceholder: 'sk-ant-...',
    proxyRoute: '/api/ai/claude',
    docsUrl: 'https://console.anthropic.com/',
    docsLabel: 'console.anthropic.com',
    color: '#9d4edd',
    requiresApiKey: true,
  },
  openai: {
    id: 'openai',
    name: 'OpenAI (GPT-4o)',
    description: 'OpenAI\'s GPT-4o — fast and versatile',
    model: 'gpt-4o',
    keyField: 'openaiApiKey',
    keyPrefix: 'sk-',
    keyPlaceholder: 'sk-...',
    proxyRoute: '/api/ai/openai',
    docsUrl: 'https://platform.openai.com/api-keys',
    docsLabel: 'platform.openai.com',
    color: '#10a37f',
    requiresApiKey: true,
  },
  gemini: {
    id: 'gemini',
    name: 'Google Gemini',
    description: 'Google\'s Gemini — great at multi-step reasoning',
    model: 'gemini-2.0-flash',
    keyField: 'geminiApiKey',
    keyPrefix: '',
    keyPlaceholder: 'AIza...',
    proxyRoute: '/api/ai/gemini',
    docsUrl: 'https://aistudio.google.com/apikey',
    docsLabel: 'aistudio.google.com',
    color: '#4285f4',
    requiresApiKey: true,
  },
  ollama: {
    id: 'ollama',
    name: 'Ollama (Local)',
    description: 'Run models locally — free, private, no API key needed',
    model: 'llama3.2',
    keyField: null,
    keyPrefix: null,
    keyPlaceholder: null,
    proxyRoute: '/api/ai/ollama',
    docsUrl: 'https://ollama.com/',
    docsLabel: 'ollama.com',
    color: '#ffffff',
    requiresApiKey: false,
  },
};

export const PROVIDER_IDS = Object.keys(AI_PROVIDERS);
